"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus } from "lucide-react";
import { Button, Checkbox, DataTable, Dialog, Field, Input, PageHeader, Skeleton, StatusBadge } from "@/components/ui";
import { usePerm } from "@/components/admin/shared";
import { del, get, post, put } from "@/lib/api";
import { useUi } from "@/stores/ui";
export default function CollectionsPage() {
  const qc = useQueryClient(); const toast = useUi((s) => s.toast); const can = usePerm();
  const [edit, setEdit] = useState<any>(null);
  const { data, isLoading } = useQuery({ queryKey: ["admin-cols"], queryFn: async () => (await get("/admin/collections")).data });
  const inv = () => qc.invalidateQueries({ queryKey: ["admin-cols"] });
  const save = useMutation({ mutationFn: (c: any) => { const body = { name: c.name, slug: c.slug || undefined, description: c.description || null, imageUrl: c.imageUrl || null, isFeatured: !!c.isFeatured, isActive: !!c.isActive, sortOrder: Number(c.sortOrder ?? 0) }; return c.id ? put(`/admin/collections/${c.id}`, body) : post("/admin/collections", body); }, onSuccess: () => { inv(); setEdit(null); toast({ title: "Collection saved", variant: "success" }); }, onError: (e: any) => toast({ title: e.message, variant: "error" }) });
  const remove = useMutation({ mutationFn: (id: number) => del(`/admin/collections/${id}`), onSuccess: inv, onError: (e: any) => toast({ title: e.message, variant: "error" }) });
  if (isLoading) return <Skeleton className="h-64" />;
  return <div><PageHeader title="Collections" description="Curated groupings of products. Assign products from the product editor." actions={can("PRODUCT_CREATE") && <Button onClick={() => setEdit({ name: "", slug: "", description: "", imageUrl: "", isFeatured: false, isActive: true, sortOrder: 0 })}><Plus className="h-4 w-4" /> New collection</Button>} />
    <DataTable rows={data ?? []} keyField="id" columns={[{ key: "name", header: "Collection", render: (c: any) => <div className="flex items-center gap-3">{c.imageUrl && <img src={c.imageUrl} alt="" className="h-10 w-10 rounded-md object-cover" />}<div><p className="font-medium">{c.name}</p><p className="text-xs text-stone">{c.description}</p></div></div> }, { key: "slug", header: "Slug", render: (c: any) => <span className="font-mono text-xs">/collections/{c.slug}</span> }, { key: "productCount", header: "Products" }, { key: "isFeatured", header: "Featured", render: (c: any) => (c.isFeatured ? "Yes" : "—") }, { key: "isActive", header: "Status", render: (c: any) => <StatusBadge status={c.isActive ? "ACTIVE" : "INACTIVE"} /> }, { key: "actions", header: "", render: (c: any) => can("PRODUCT_UPDATE") && <div className="flex justify-end gap-2"><Button size="sm" variant="ghost" onClick={() => setEdit({ ...c, description: c.description ?? "", imageUrl: c.imageUrl ?? "" })}>Edit</Button>{can("PRODUCT_DELETE") && <Button size="sm" variant="ghost" className="text-red-600" onClick={() => { if (confirm("Delete collection?")) remove.mutate(c.id); }}>Delete</Button>}</div>, className: "text-right" }]} />
    <Dialog open={!!edit} onClose={() => setEdit(null)} title={edit?.id ? "Edit collection" : "New collection"}>{edit && <form className="space-y-3" onSubmit={(e) => { e.preventDefault(); save.mutate(edit); }}><Field label="Name"><Input required value={edit.name} onChange={(e) => setEdit({ ...edit, name: e.target.value })} /></Field><Field label="Slug"><Input value={edit.slug} onChange={(e) => setEdit({ ...edit, slug: e.target.value })} /></Field><Field label="Description"><Input value={edit.description} onChange={(e) => setEdit({ ...edit, description: e.target.value })} /></Field><Field label="Image URL"><Input value={edit.imageUrl} onChange={(e) => setEdit({ ...edit, imageUrl: e.target.value })} /></Field><div className="flex gap-6 pt-1"><Checkbox label="Featured on homepage" checked={!!edit.isFeatured} onChange={(e) => setEdit({ ...edit, isFeatured: e.target.checked })} /><Checkbox label="Active" checked={!!edit.isActive} onChange={(e) => setEdit({ ...edit, isActive: e.target.checked })} /></div><Button type="submit" className="w-full" loading={save.isPending}>Save</Button></form>}</Dialog></div>;
}
