"use client";
import Link from "next/link";
import { use, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Trash2, ExternalLink } from "lucide-react";
import { Button, Card, Checkbox, ErrorState, Field, Input, PageHeader, Select, Skeleton, StatusBadge, Textarea, DataTable } from "@/components/ui";
import { get, post, put } from "@/lib/api";
import { cn, formatDateTime } from "@/lib/utils";
import { useUi } from "@/stores/ui";

const TABS = ["General", "Pricing & Variants", "Images", "Inventory", "Categories", "SEO", "Sustainability", "Shipping"];
const blank = { name: "", slug: "", description: "", shortDescription: "", status: "DRAFT", productType: "shoes", gender: "unisex", primaryCategoryId: null as number | null, material: "", careInstructions: "", sustainabilityDescription: "", specifications: {} as Record<string, string>, seoTitle: "", seoDescription: "", weightGrams: null as number | null, shippingClass: "standard", isFeatured: false, isBestSeller: false, categoryIds: [] as number[], collectionIds: [] as number[], tags: [] as string[], images: [] as any[], variants: [] as any[] };

export default function ProductEditor({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const isNew = id === "new";
  const router = useRouter();
  const qc = useQueryClient();
  const toast = useUi((s) => s.toast);
  const [tab, setTab] = useState(0);
  const [f, setF] = useState<any>(blank);
  const [specKey, setSpecKey] = useState(""); const [specVal, setSpecVal] = useState("");
  const { data, isLoading, isError } = useQuery({ queryKey: ["admin-product", id], queryFn: async () => (await get(`/admin/products/${id}`)).data, enabled: !isNew });
  const { data: cats } = useQuery({ queryKey: ["admin-cats"], queryFn: async () => (await get("/admin/categories")).data });
  const { data: cols } = useQuery({ queryKey: ["admin-cols"], queryFn: async () => (await get("/admin/collections")).data });
  const { data: txs } = useQuery({ queryKey: ["inv-tx-product", id], queryFn: async () => (await get(`/admin/inventory/transactions?pageSize=15`)).data, enabled: !isNew && tab === 3 });
  useEffect(() => { if (data) setF({ ...blank, ...data, shortDescription: data.shortDescription ?? "", material: data.material ?? "", careInstructions: data.careInstructions ?? "", sustainabilityDescription: data.sustainabilityDescription ?? "", seoTitle: data.seoTitle ?? "", seoDescription: data.seoDescription ?? "", specifications: data.specifications ?? {}, categoryIds: data.categories.map((c: any) => c.id), collectionIds: data.collections.map((c: any) => c.id), images: data.images.map((i: any) => ({ url: i.url, altText: i.altText ?? "", color: i.color ?? "", sortOrder: i.sortOrder })), variants: data.variants.map((v: any) => ({ ...v, compareAtPrice: v.compareAtPrice ?? "", costPrice: v.costPrice ?? "", barcode: v.barcode ?? "", weightGrams: v.weightGrams ?? "" })) }); }, [data]);
  const save = useMutation({
    mutationFn: () => { const payload = { ...f, primaryCategoryId: f.primaryCategoryId ? Number(f.primaryCategoryId) : null, weightGrams: f.weightGrams ? Number(f.weightGrams) : null, images: f.images.map((i: any, idx: number) => ({ url: i.url, altText: i.altText || null, color: i.color || null, sortOrder: idx })), variants: f.variants.map((v: any) => ({ id: v.id, sku: v.sku, color: v.color, colorHex: v.colorHex || "#000000", size: v.size, price: Number(v.price), compareAtPrice: v.compareAtPrice !== "" && v.compareAtPrice != null ? Number(v.compareAtPrice) : null, costPrice: v.costPrice !== "" && v.costPrice != null ? Number(v.costPrice) : null, barcode: v.barcode || null, weightGrams: v.weightGrams !== "" && v.weightGrams != null ? Number(v.weightGrams) : null, status: v.status ?? "ACTIVE", initialStock: v.initialStock ? Number(v.initialStock) : undefined })) }; delete payload.categories; delete payload.collections; delete payload.ratingDistribution; delete payload.brand; delete payload.primaryCategory; delete payload.colors; delete payload.id; delete payload.price; delete payload.compareAtPrice; delete payload.createdAt; delete payload.updatedAt; delete payload.publishedAt; delete payload.ratingAvg; delete payload.ratingCount; delete payload.brandId; return isNew ? post("/admin/products", payload) : put(`/admin/products/${id}`, payload); },
    onSuccess: (r) => { qc.invalidateQueries({ queryKey: ["/admin/products"] }); qc.invalidateQueries({ queryKey: ["admin-product", id] }); toast({ title: isNew ? "Product created" : "Product saved", variant: "success" }); if (isNew) router.replace(`/admin/products/${r.data.id}`); },
    onError: (e: any) => toast({ title: e.message, description: e.details ? JSON.stringify(e.details).slice(0, 200) : undefined, variant: "error" }),
  });
  if (!isNew && isLoading) return <Skeleton className="h-96" />;
  if (isError) return <ErrorState title="Product not found" />;
  const up = (k: string, v: any) => setF((p: any) => ({ ...p, [k]: v }));
  const upVariant = (i: number, k: string, v: any) => setF((p: any) => ({ ...p, variants: p.variants.map((x: any, idx: number) => (idx === i ? { ...x, [k]: v } : x)) }));
  const generateVariants = () => { const colors = prompt("Colors (comma separated, e.g. Black:#111111, Moss:#6B7A5A)") ?? ""; const sizes = prompt("Sizes (comma separated)") ?? ""; const price = Number(prompt("Base price", "98") ?? 0); if (!colors || !sizes) return; const base = (f.slug || f.name).toUpperCase().replace(/[^A-Z0-9]+/g, "-").slice(0, 12); const vs = colors.split(",").flatMap((c, ci) => { const [name, hex] = c.split(":").map((x) => x.trim()); return sizes.split(",").map((s) => ({ sku: `${base}-${ci + 1}-${s.trim().toUpperCase()}`, color: name, colorHex: hex || "#000000", size: s.trim(), price, compareAtPrice: "", costPrice: "", barcode: "", weightGrams: "", status: "ACTIVE", initialStock: 10 })); }); up("variants", [...f.variants, ...vs]); };
  const toggleId = (k: string, id: number) => up(k, f[k].includes(id) ? f[k].filter((x: number) => x !== id) : [...f[k], id]);
  return (
    <div>
      <PageHeader crumbs={[{ label: "Products", href: "/admin/products" }, { label: isNew ? "New" : f.name }]} title={isNew ? "New product" : f.name || "Product"} description={!isNew ? `Last updated ${formatDateTime(data?.updatedAt)}` : undefined} actions={<>{!isNew && <StatusBadge status={f.status} />}{!isNew && <Link href={`/products/${f.slug}`} target="_blank" className="flex items-center gap-1 rounded-full border border-ink/15 px-4 py-2 text-sm hover:bg-ink/5"><ExternalLink className="h-4 w-4" /> View</Link>}<Button onClick={() => save.mutate()} loading={save.isPending}>{isNew ? "Create product" : "Save changes"}</Button></>} />
      <div className="mb-5 flex gap-1 overflow-x-auto border-b border-ink/10 no-scrollbar">{TABS.map((t, i) => <button key={t} onClick={() => setTab(i)} className={cn("shrink-0 border-b-2 px-4 py-2.5 text-sm", tab === i ? "border-ink font-medium" : "border-transparent text-stone hover:text-ink")}>{t}</button>)}</div>
      <Card className="p-6">
        {tab === 0 && <div className="grid gap-5 lg:grid-cols-[1fr_280px]"><div className="space-y-4"><Field label="Name"><Input value={f.name} onChange={(e) => up("name", e.target.value)} /></Field><Field label="Slug"><Input value={f.slug} onChange={(e) => up("slug", e.target.value)} placeholder="auto-generated from name" /></Field><Field label="Short description"><Input value={f.shortDescription} onChange={(e) => up("shortDescription", e.target.value)} /></Field><Field label="Description"><Textarea rows={8} value={f.description} onChange={(e) => up("description", e.target.value)} /></Field></div><div className="space-y-4"><Field label="Status"><Select value={f.status} onChange={(e) => up("status", e.target.value)}><option>DRAFT</option><option>ACTIVE</option><option>ARCHIVED</option></Select></Field><Field label="Product type"><Select value={f.productType} onChange={(e) => up("productType", e.target.value)}><option value="shoes">Shoes</option><option value="apparel">Apparel</option><option value="accessories">Accessories</option></Select></Field><Field label="Gender"><Select value={f.gender} onChange={(e) => up("gender", e.target.value)}><option value="unisex">Unisex</option><option value="men">Men</option><option value="women">Women</option></Select></Field><Field label="Primary category"><Select value={f.primaryCategoryId ?? ""} onChange={(e) => up("primaryCategoryId", e.target.value || null)}><option value="">—</option>{cats?.map((c: any) => <option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field><Checkbox label="Featured on homepage" checked={f.isFeatured} onChange={(e) => up("isFeatured", e.target.checked)} /><Checkbox label="Best seller badge" checked={f.isBestSeller} onChange={(e) => up("isBestSeller", e.target.checked)} /><Field label="Tags (comma separated)"><Input value={f.tags.join(", ")} onChange={(e) => up("tags", e.target.value.split(",").map((x) => x.trim()).filter(Boolean))} /></Field></div></div>}
        {tab === 1 && <div><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><p className="text-sm text-stone">{f.variants.length} variants. Each SKU carries its own price, barcode, weight and inventory.</p><div className="flex gap-2"><Button variant="outline" size="sm" onClick={generateVariants}>Generate matrix</Button><Button size="sm" onClick={() => up("variants", [...f.variants, { sku: "", color: "", colorHex: "#000000", size: "", price: f.variants[0]?.price ?? 0, compareAtPrice: "", costPrice: "", barcode: "", weightGrams: "", status: "ACTIVE", initialStock: 0 }])}><Plus className="h-4 w-4" /> Add variant</Button></div></div>
          <div className="overflow-x-auto"><table className="w-full min-w-[960px] text-xs"><thead><tr className="border-b border-ink/10 text-left uppercase tracking-wider text-stone"><th className="py-2 pr-2">SKU</th><th className="pr-2">Color</th><th className="pr-2">Hex</th><th className="pr-2">Size</th><th className="pr-2">Price</th><th className="pr-2">Compare at</th><th className="pr-2">Cost</th><th className="pr-2">Barcode</th><th className="pr-2">Weight (g)</th><th className="pr-2">{isNew ? "Initial stock" : "Available"}</th><th className="pr-2">Status</th><th /></tr></thead><tbody>
            {f.variants.map((v: any, i: number) => <tr key={v.id ?? i} className="border-b border-ink/5">{[["sku", "text", 130], ["color", "text", 90], ["colorHex", "color", 40], ["size", "text", 60], ["price", "number", 70], ["compareAtPrice", "number", 70], ["costPrice", "number", 70], ["barcode", "text", 110], ["weightGrams", "number", 70]].map(([k, type, w]) => <td key={k as string} className="py-1 pr-2"><input type={type as string} value={v[k as string] ?? ""} onChange={(e) => upVariant(i, k as string, e.target.value)} className="h-8 rounded border border-ink/15 px-2" style={{ width: w as number }} /></td>)}
              <td className="pr-2">{v.id ? <span className={cn("font-semibold", v.available <= 0 ? "text-red-600" : v.available <= 5 ? "text-amber-600" : "")}>{v.available}</span> : <input type="number" min={0} value={v.initialStock ?? 0} onChange={(e) => upVariant(i, "initialStock", e.target.value)} className="h-8 w-16 rounded border border-ink/15 px-2" />}</td>
              <td className="pr-2"><select value={v.status} onChange={(e) => upVariant(i, "status", e.target.value)} className="h-8 rounded border border-ink/15 px-1"><option>ACTIVE</option><option>INACTIVE</option></select></td>
              <td><button onClick={() => up("variants", f.variants.filter((_: any, idx: number) => idx !== i))} className="p-1 text-stone hover:text-red-600" aria-label="Remove variant"><Trash2 className="h-4 w-4" /></button></td></tr>)}
          </tbody></table></div><p className="mt-3 text-xs text-stone">Removing a saved variant deactivates it (order history is preserved). New variants with initial stock create a PURCHASE ledger entry at the default warehouse.</p></div>}
        {tab === 2 && <div><div className="mb-4 flex items-center justify-between"><p className="text-sm text-stone">Images are stored via the media abstraction (local/MinIO/S3); enter a URL or choose a library asset.</p><Button size="sm" onClick={() => up("images", [...f.images, { url: "/images/products/runner.jpg", altText: "", color: "" }])}><Plus className="h-4 w-4" /> Add image</Button></div>
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{f.images.map((im: any, i: number) => <div key={i} className="rounded-xl border border-ink/10 p-3"><img src={im.url} alt="" className="aspect-[4/5] w-full rounded-lg bg-sand object-cover" /><div className="mt-2 space-y-2"><Select value={im.url} onChange={(e) => up("images", f.images.map((x: any, idx: number) => (idx === i ? { ...x, url: e.target.value } : x)))}>{["runner", "trail", "wool-sneaker", "slipon", "tee", "hoodie", "socks", "accessory"].map((k) => <option key={k} value={`/images/products/${k}.jpg`}>{k}</option>)}{!im.url.startsWith("/images/products/") && <option value={im.url}>{im.url}</option>}</Select><Input placeholder="Custom URL" value={im.url} onChange={(e) => up("images", f.images.map((x: any, idx: number) => (idx === i ? { ...x, url: e.target.value } : x)))} className="h-9 text-xs" /><Input placeholder="Color (optional)" value={im.color} onChange={(e) => up("images", f.images.map((x: any, idx: number) => (idx === i ? { ...x, color: e.target.value } : x)))} className="h-9 text-xs" /><div className="flex justify-between text-xs"><span className="text-stone">Position {i + 1}</span><button onClick={() => up("images", f.images.filter((_: any, idx: number) => idx !== i))} className="text-red-600">Remove</button></div></div></div>)}</div></div>}
        {tab === 3 && (isNew ? <p className="text-sm text-stone">Save the product first to manage inventory. Initial stock can be set per variant on the Variants tab.</p> : <div><p className="mb-3 text-sm text-stone">Stock is tracked per SKU per warehouse. Use <Link href={`/admin/inventory?q=${encodeURIComponent(f.name)}`} className="underline">Inventory</Link> to adjust levels — every change writes a ledger transaction.</p><DataTable rows={f.variants.filter((v: any) => v.id)} keyField="id" columns={[{ key: "sku", header: "SKU", render: (v: any) => <Link href={`/admin/inventory?q=${v.sku}`} className="font-mono text-xs hover:underline">{v.sku}</Link> }, { key: "color", header: "Variant", render: (v: any) => `${v.color} / ${v.size}` }, { key: "onHand", header: "On hand" }, { key: "available", header: "Available", render: (v: any) => <span className={v.available <= 0 ? "font-semibold text-red-600" : v.available <= 5 ? "font-semibold text-amber-600" : ""}>{v.available}</span> }]} /><p className="mb-2 mt-6 text-sm font-medium">Recent stock movements</p><DataTable rows={txs ?? []} keyField="id" columns={[{ key: "createdAt", header: "When", render: (t: any) => formatDateTime(t.createdAt) }, { key: "sku", header: "SKU" }, { key: "warehouseCode", header: "WH" }, { key: "type", header: "Type" }, { key: "quantity", header: "Qty" }, { key: "reason", header: "Reason" }]} /></div>)}
        {tab === 4 && <div className="grid gap-8 md:grid-cols-2"><div><p className="mb-2 text-sm font-medium">Categories</p><div className="grid gap-1.5">{cats?.map((c: any) => <Checkbox key={c.id} label={<span className={c.parentId ? "pl-4" : "font-medium"}>{c.name}</span>} checked={f.categoryIds.includes(c.id)} onChange={() => toggleId("categoryIds", c.id)} />)}</div></div><div><p className="mb-2 text-sm font-medium">Collections</p><div className="grid gap-1.5">{cols?.map((c: any) => <Checkbox key={c.id} label={c.name} checked={f.collectionIds.includes(c.id)} onChange={() => toggleId("collectionIds", c.id)} />)}</div></div></div>}
        {tab === 5 && <div className="max-w-xl space-y-4"><Field label="SEO title"><Input value={f.seoTitle} onChange={(e) => up("seoTitle", e.target.value)} maxLength={160} /></Field><Field label="Meta description"><Textarea value={f.seoDescription} onChange={(e) => up("seoDescription", e.target.value)} maxLength={320} /></Field><div className="rounded-xl bg-bone p-4"><p className="text-xs text-stone">Preview</p><p className="text-base text-blue-800">{f.seoTitle || f.name} | Evergreen</p><p className="text-xs text-emerald-700">evergreen.example/products/{f.slug || "slug"}</p><p className="text-sm text-stone">{f.seoDescription || f.shortDescription}</p></div></div>}
        {tab === 6 && <div className="max-w-2xl space-y-4"><Field label="Materials"><Textarea value={f.material} onChange={(e) => up("material", e.target.value)} /></Field><Field label="Care instructions"><Textarea value={f.careInstructions} onChange={(e) => up("careInstructions", e.target.value)} /></Field><Field label="Sustainability story"><Textarea rows={5} value={f.sustainabilityDescription} onChange={(e) => up("sustainabilityDescription", e.target.value)} /></Field><div><p className="mb-2 text-xs font-medium uppercase tracking-wider text-ink/70">Specifications</p><ul className="mb-2 space-y-1 text-sm">{Object.entries(f.specifications).map(([k, v]) => <li key={k} className="flex justify-between rounded bg-bone px-3 py-1.5"><span><strong>{k}</strong>: {v as string}</span><button onClick={() => { const s = { ...f.specifications }; delete s[k]; up("specifications", s); }} className="text-xs text-red-600">Remove</button></li>)}</ul><div className="flex gap-2"><Input placeholder="Key" value={specKey} onChange={(e) => setSpecKey(e.target.value)} /><Input placeholder="Value" value={specVal} onChange={(e) => setSpecVal(e.target.value)} /><Button variant="outline" onClick={() => { if (specKey) { up("specifications", { ...f.specifications, [specKey]: specVal }); setSpecKey(""); setSpecVal(""); } }}>Add</Button></div></div></div>}
        {tab === 7 && <div className="max-w-md space-y-4"><Field label="Weight (grams)"><Input type="number" value={f.weightGrams ?? ""} onChange={(e) => up("weightGrams", e.target.value)} /></Field><Field label="Shipping class"><Select value={f.shippingClass ?? "standard"} onChange={(e) => up("shippingClass", e.target.value)}><option value="standard">Standard</option><option value="oversized">Oversized</option><option value="light">Light (letter)</option></Select></Field></div>}
      </Card>
    </div>
  );
}
