"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, ArrowRight } from "lucide-react";
import { Button, Card, Checkbox, DataTable, Dialog, Field, Input, PageHeader, Select, Skeleton, StatusBadge, Textarea } from "@/components/ui";
import { usePerm } from "@/components/admin/shared";
import { get, patch, post, put } from "@/lib/api";
import { formatDateTime } from "@/lib/utils";
import { useUi } from "@/stores/ui";
const blank = { code: "", name: "", status: "ACTIVE", addressLine1: "", city: "", region: "", postalCode: "", country: "US", isDefault: false, priority: 100 };
const NEXT: Record<string, string[]> = { REQUESTED: ["APPROVED", "CANCELLED"], APPROVED: ["IN_TRANSIT", "CANCELLED"], IN_TRANSIT: ["COMPLETED"] };
export default function WarehousesPage() {
  const qc = useQueryClient();
  const toast = useUi((s) => s.toast);
  const can = usePerm();
  const [edit, setEdit] = useState<any>(null);
  const [transfer, setTransfer] = useState<any>(null);
  const { data: whs, isLoading } = useQuery({ queryKey: ["warehouses"], queryFn: async () => (await get("/admin/warehouses")).data });
  const { data: transfers } = useQuery({ queryKey: ["transfers"], queryFn: async () => (await get("/admin/transfers")).data });
  const onError = (e: any) => toast({ title: e.message, variant: "error" });
  const save = useMutation({ mutationFn: (w: any) => (w.id ? put(`/admin/warehouses/${w.id}`, w) : post("/admin/warehouses", w)), onSuccess: () => { qc.invalidateQueries({ queryKey: ["warehouses"] }); setEdit(null); toast({ title: "Warehouse saved", variant: "success" }); }, onError });
  const createT = useMutation({ mutationFn: (t: any) => post("/admin/transfers", t), onSuccess: () => { qc.invalidateQueries({ queryKey: ["transfers"] }); setTransfer(null); toast({ title: "Transfer requested", variant: "success" }); }, onError });
  const moveT = useMutation({ mutationFn: (v: { id: number; status: string }) => patch(`/admin/transfers/${v.id}/status`, { status: v.status }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["transfers"] }); qc.invalidateQueries({ queryKey: ["warehouses"] }); toast({ title: "Transfer updated", variant: "success" }); }, onError });
  if (isLoading) return <Skeleton className="h-64" />;
  return (
    <div>
      <PageHeader title="Warehouses" description="Fulfillment locations and stock transfers between them." actions={can("INVENTORY_TRANSFER") && <><Button variant="outline" onClick={() => setTransfer({ fromWarehouseId: whs?.[0]?.id, toWarehouseId: whs?.[1]?.id, notes: "", items: [{ sku: "", quantity: 1 }] })}><ArrowRight className="h-4 w-4" /> New transfer</Button><Button onClick={() => setEdit({ ...blank })}><Plus className="h-4 w-4" /> Add warehouse</Button></>} />
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{whs?.map((w: any) => <Card key={w.id} className="p-5"><div className="flex items-start justify-between"><div><p className="font-display text-xl">{w.code}</p><p className="text-sm">{w.name}</p></div><div className="flex flex-col items-end gap-1"><StatusBadge status={w.status} />{w.isDefault && <span className="text-[10px] font-semibold uppercase text-forest">Default</span>}</div></div><p className="mt-2 text-xs text-stone">{w.addressLine1}, {w.city}, {w.region} {w.postalCode}</p><dl className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-lg bg-bone p-2"><dt className="text-stone">SKUs</dt><dd className="font-semibold">{w.skus}</dd></div><div className="rounded-lg bg-bone p-2"><dt className="text-stone">On hand</dt><dd className="font-semibold">{w.onHand.toLocaleString()}</dd></div><div className="rounded-lg bg-bone p-2"><dt className="text-stone">Low</dt><dd className="font-semibold text-amber-600">{w.low}</dd></div></dl><div className="mt-4 flex gap-3 text-xs"><a href={`/admin/inventory?warehouseId=${w.id}`} className="underline-offset-4 hover:underline">View inventory</a>{can("INVENTORY_TRANSFER") && <button onClick={() => setEdit({ ...blank, ...w })} className="underline-offset-4 hover:underline">Edit</button>}</div></Card>)}</div>
      <h2 className="mb-3 mt-10 font-display text-2xl">Stock transfers</h2>
      <DataTable rows={transfers ?? []} keyField="id" empty="No transfers yet" columns={[{ key: "id", header: "#", render: (t: any) => `TR-${t.id}` }, { key: "route", header: "Route", render: (t: any) => <span className="font-medium">{t.fromCode} → {t.toCode}</span> }, { key: "units", header: "Units", render: (t: any) => `${t.units} (${t.itemCount} SKUs)` }, { key: "status", header: "Status", render: (t: any) => <StatusBadge status={t.status} /> }, { key: "createdAt", header: "Created", render: (t: any) => formatDateTime(t.createdAt) }, { key: "notes", header: "Notes" }, { key: "actions", header: "", render: (t: any) => can("INVENTORY_TRANSFER") && <div className="flex justify-end gap-1">{(NEXT[t.status] ?? []).map((s) => <Button key={s} size="sm" variant={s === "CANCELLED" ? "ghost" : "outline"} onClick={() => moveT.mutate({ id: t.id, status: s })}>{s.replace("_", " ")}</Button>)}</div>, className: "text-right" }]} />
      <Dialog open={!!edit} onClose={() => setEdit(null)} title={edit?.id ? "Edit warehouse" : "New warehouse"}>{edit && <form className="space-y-3" onSubmit={(e) => { e.preventDefault(); const { skus, onHand, reserved, low, createdAt, ...w } = edit; save.mutate({ ...w, priority: Number(w.priority) }); }}><div className="grid grid-cols-2 gap-3"><Field label="Code"><Input required value={edit.code} onChange={(e) => setEdit({ ...edit, code: e.target.value.toUpperCase() })} /></Field><Field label="Status"><Select value={edit.status} onChange={(e) => setEdit({ ...edit, status: e.target.value })}><option>ACTIVE</option><option>INACTIVE</option></Select></Field></div><Field label="Name"><Input required value={edit.name} onChange={(e) => setEdit({ ...edit, name: e.target.value })} /></Field><Field label="Address"><Input value={edit.addressLine1 ?? ""} onChange={(e) => setEdit({ ...edit, addressLine1: e.target.value })} /></Field><div className="grid grid-cols-3 gap-3"><Field label="City"><Input value={edit.city ?? ""} onChange={(e) => setEdit({ ...edit, city: e.target.value })} /></Field><Field label="Region"><Input value={edit.region ?? ""} onChange={(e) => setEdit({ ...edit, region: e.target.value })} /></Field><Field label="Postal"><Input value={edit.postalCode ?? ""} onChange={(e) => setEdit({ ...edit, postalCode: e.target.value })} /></Field></div><div className="grid grid-cols-2 gap-3"><Field label="Priority (lower ships first)"><Input type="number" value={edit.priority} onChange={(e) => setEdit({ ...edit, priority: e.target.value })} /></Field><div className="pt-6"><Checkbox label="Default warehouse" checked={!!edit.isDefault} onChange={(e) => setEdit({ ...edit, isDefault: e.target.checked })} /></div></div><Button type="submit" className="w-full" loading={save.isPending}>Save</Button></form>}</Dialog>
      <Dialog open={!!transfer} onClose={() => setTransfer(null)} title="New stock transfer">{transfer && <form className="space-y-3" onSubmit={(e) => { e.preventDefault(); createT.mutate({ ...transfer, fromWarehouseId: Number(transfer.fromWarehouseId), toWarehouseId: Number(transfer.toWarehouseId), items: transfer.items.map((i: any) => ({ sku: i.sku, quantity: Number(i.quantity) })) }); }}><div className="grid grid-cols-2 gap-3"><Field label="From"><Select value={transfer.fromWarehouseId} onChange={(e) => setTransfer({ ...transfer, fromWarehouseId: e.target.value })}>{whs?.map((w: any) => <option key={w.id} value={w.id}>{w.code}</option>)}</Select></Field><Field label="To"><Select value={transfer.toWarehouseId} onChange={(e) => setTransfer({ ...transfer, toWarehouseId: e.target.value })}>{whs?.map((w: any) => <option key={w.id} value={w.id}>{w.code}</option>)}</Select></Field></div><p className="text-xs font-medium uppercase tracking-wider text-ink/70">Items (by SKU)</p>{transfer.items.map((it: any, i: number) => <div key={i} className="flex gap-2"><Input placeholder="EG-0001-01-42" value={it.sku} onChange={(e) => setTransfer({ ...transfer, items: transfer.items.map((x: any, idx: number) => (idx === i ? { ...x, sku: e.target.value } : x)) })} /><Input type="number" min={1} className="w-24" value={it.quantity} onChange={(e) => setTransfer({ ...transfer, items: transfer.items.map((x: any, idx: number) => (idx === i ? { ...x, quantity: e.target.value } : x)) })} /></div>)}<button type="button" onClick={() => setTransfer({ ...transfer, items: [...transfer.items, { sku: "", quantity: 1 }] })} className="text-xs underline">+ Add line</button><Field label="Notes"><Textarea value={transfer.notes} onChange={(e) => setTransfer({ ...transfer, notes: e.target.value })} /></Field><Button type="submit" className="w-full" loading={createT.isPending}>Request transfer</Button><p className="text-xs text-stone">Flow: REQUESTED → APPROVED → IN_TRANSIT (stock leaves source) → COMPLETED (stock arrives at destination).</p></form>}</Dialog>
    </div>
  );
}
