"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus } from "lucide-react";
import { Button, Checkbox, DataTable, Dialog, Field, Input, PageHeader, Select, Skeleton, StatusBadge } from "@/components/ui";
import { usePerm } from "@/components/admin/shared";
import { get, patch, post, put } from "@/lib/api";
import { formatDate, formatMoney } from "@/lib/utils";
import { useUi } from "@/stores/ui";
const blank = { code: "", description: "", type: "PERCENTAGE", value: 10, minimumOrderAmount: "", usageLimit: "", perCustomerLimit: "", startsAt: "", expiresAt: "", isActive: true, appliesToProductType: "", appliesToCategoryId: "" };
export default function PromotionsPage() {
  const qc = useQueryClient();
  const toast = useUi((s) => s.toast);
  const can = usePerm();
  const [edit, setEdit] = useState<any>(null);
  const { data, isLoading } = useQuery({ queryKey: ["coupons"], queryFn: async () => (await get("/admin/promotions")).data });
  const { data: cats } = useQuery({ queryKey: ["admin-cats"], queryFn: async () => (await get("/admin/categories")).data });
  const onError = (e: any) => toast({ title: e.message, variant: "error" });
  const save = useMutation({ mutationFn: (c: any) => { const body = { ...c, value: Number(c.value), minimumOrderAmount: c.minimumOrderAmount === "" ? null : Number(c.minimumOrderAmount), usageLimit: c.usageLimit === "" ? null : Number(c.usageLimit), perCustomerLimit: c.perCustomerLimit === "" ? null : Number(c.perCustomerLimit), startsAt: c.startsAt || null, expiresAt: c.expiresAt || null, appliesToProductType: c.appliesToProductType || null, appliesToCategoryId: c.appliesToCategoryId ? Number(c.appliesToCategoryId) : null }; delete body.id; delete body.usageCount; delete body.createdAt; return c.id ? put(`/admin/promotions/${c.id}`, body) : post("/admin/promotions", body); }, onSuccess: () => { qc.invalidateQueries({ queryKey: ["coupons"] }); setEdit(null); toast({ title: "Coupon saved", variant: "success" }); }, onError });
  const toggle = useMutation({ mutationFn: (c: any) => patch(`/admin/promotions/${c.id}`, { isActive: !c.isActive }), onSuccess: () => qc.invalidateQueries({ queryKey: ["coupons"] }), onError });
  if (isLoading) return <Skeleton className="h-64" />;
  const fmt = (d: string | null) => (d ? new Date(d).toISOString().slice(0, 10) : "");
  return (
    <div>
      <PageHeader title="Promotions" description="Coupon codes with usage limits, expiry, minimums and product restrictions." actions={can("PRODUCT_UPDATE") && <Button onClick={() => setEdit({ ...blank })}><Plus className="h-4 w-4" /> New coupon</Button>} />
      <DataTable rows={data ?? []} keyField="id" columns={[{ key: "code", header: "Code", render: (c: any) => <div><p className="font-mono font-semibold">{c.code}</p><p className="text-xs text-stone">{c.description}</p></div> }, { key: "type", header: "Discount", render: (c: any) => (c.type === "PERCENTAGE" ? `${Number(c.value)}% off` : c.type === "FIXED_AMOUNT" ? `${formatMoney(c.value)} off` : "Free shipping") }, { key: "min", header: "Min. order", render: (c: any) => (c.minimumOrderAmount ? formatMoney(c.minimumOrderAmount) : "—") }, { key: "usage", header: "Usage", render: (c: any) => `${c.usageCount}${c.usageLimit ? ` / ${c.usageLimit}` : ""}` }, { key: "expiresAt", header: "Expires", render: (c: any) => (c.expiresAt ? <span className={new Date(c.expiresAt) < new Date() ? "text-red-600" : ""}>{formatDate(c.expiresAt)}</span> : "Never") }, { key: "isActive", header: "Status", render: (c: any) => <StatusBadge status={c.isActive ? (c.expiresAt && new Date(c.expiresAt) < new Date() ? "INACTIVE" : "ACTIVE") : "DISABLED"} /> }, { key: "actions", header: "", render: (c: any) => can("PRODUCT_UPDATE") && <div className="flex justify-end gap-2"><Button size="sm" variant="ghost" onClick={() => setEdit({ ...blank, ...c, minimumOrderAmount: c.minimumOrderAmount ?? "", usageLimit: c.usageLimit ?? "", perCustomerLimit: c.perCustomerLimit ?? "", startsAt: fmt(c.startsAt), expiresAt: fmt(c.expiresAt), appliesToProductType: c.appliesToProductType ?? "", appliesToCategoryId: c.appliesToCategoryId ?? "" })}>Edit</Button><Button size="sm" variant="outline" onClick={() => toggle.mutate(c)}>{c.isActive ? "Deactivate" : "Activate"}</Button></div>, className: "text-right" }]} />
      <Dialog open={!!edit} onClose={() => setEdit(null)} title={edit?.id ? `Edit ${edit.code}` : "New coupon"}>{edit && <form className="space-y-3" onSubmit={(e) => { e.preventDefault(); save.mutate(edit); }}><div className="grid grid-cols-2 gap-3"><Field label="Code"><Input required value={edit.code} onChange={(e) => setEdit({ ...edit, code: e.target.value.toUpperCase() })} /></Field><Field label="Type"><Select value={edit.type} onChange={(e) => setEdit({ ...edit, type: e.target.value })}><option value="PERCENTAGE">Percentage</option><option value="FIXED_AMOUNT">Fixed amount</option><option value="FREE_SHIPPING">Free shipping</option></Select></Field></div><Field label="Description"><Input value={edit.description ?? ""} onChange={(e) => setEdit({ ...edit, description: e.target.value })} /></Field><div className="grid grid-cols-2 gap-3"><Field label={edit.type === "PERCENTAGE" ? "Percent off" : "Amount off"}><Input type="number" step="0.01" min={0} value={edit.value} onChange={(e) => setEdit({ ...edit, value: e.target.value })} /></Field><Field label="Minimum order ($)"><Input type="number" step="0.01" value={edit.minimumOrderAmount} onChange={(e) => setEdit({ ...edit, minimumOrderAmount: e.target.value })} /></Field><Field label="Usage limit"><Input type="number" value={edit.usageLimit} onChange={(e) => setEdit({ ...edit, usageLimit: e.target.value })} /></Field><Field label="Per-customer limit"><Input type="number" value={edit.perCustomerLimit} onChange={(e) => setEdit({ ...edit, perCustomerLimit: e.target.value })} /></Field><Field label="Starts"><Input type="date" value={edit.startsAt} onChange={(e) => setEdit({ ...edit, startsAt: e.target.value })} /></Field><Field label="Expires"><Input type="date" value={edit.expiresAt} onChange={(e) => setEdit({ ...edit, expiresAt: e.target.value })} /></Field><Field label="Restrict to type"><Select value={edit.appliesToProductType} onChange={(e) => setEdit({ ...edit, appliesToProductType: e.target.value })}><option value="">Any</option><option value="shoes">Shoes</option><option value="apparel">Apparel</option><option value="accessories">Accessories</option></Select></Field><Field label="Restrict to category"><Select value={edit.appliesToCategoryId} onChange={(e) => setEdit({ ...edit, appliesToCategoryId: e.target.value })}><option value="">Any</option>{cats?.map((c: any) => <option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field></div><Checkbox label="Active" checked={!!edit.isActive} onChange={(e) => setEdit({ ...edit, isActive: e.target.checked })} /><Button type="submit" className="w-full" loading={save.isPending}>Save coupon</Button></form>}</Dialog>
    </div>
  );
}
