"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus } from "lucide-react";
import { Button, Checkbox, DataTable, Dialog, Field, Input, PageHeader, Select, Skeleton, StatusBadge } from "@/components/ui";
import { usePerm } from "@/components/admin/shared";
import { del, get, post, put } from "@/lib/api";
import { useUi } from "@/stores/ui";
export default function CategoriesPage() {
  const qc = useQueryClient(); const toast = useUi((s) => s.toast); const can = usePerm();
  const [edit, setEdit] = useState<any>(null);
  const { data, isLoading } = useQuery({ queryKey: ["admin-cats"], queryFn: async () => (await get("/admin/categories")).data });
  const inv = () => { qc.invalidateQueries({ queryKey: ["admin-cats"] }); };
  const save = useMutation({ mutationFn: (c: any) => { const body = { name: c.name, slug: c.slug || undefined, description: c.description || null, imageUrl: c.imageUrl || null, parentId: c.parentId ? Number(c.parentId) : null, isActive: !!c.isActive, sortOrder: Number(c.sortOrder ?? 0) }; return c.id ? put(`/admin/categories/${c.id}`, body) : post("/admin/categories", body); }, onSuccess: () => { inv(); setEdit(null); toast({ title: "Category saved", variant: "success" }); }, onError: (e: any) => toast({ title: e.message, variant: "error" }) });
  const remove = useMutation({ mutationFn: (id: number) => del(`/admin/categories/${id}`), onSuccess: inv, onError: (e: any) => toast({ title: e.message, variant: "error" }) });
  if (isLoading) return <Skeleton className="h-64" />;
  const parents = data?.filter((c: any) => !c.parentId) ?? [];
  return <div><PageHeader title="Categories" description="Hierarchical product categories." actions={can("PRODUCT_CREATE") && <Button onClick={() => setEdit({ name: "", slug: "", description: "", imageUrl: "", parentId: "", isActive: true, sortOrder: 0 })}><Plus className="h-4 w-4" /> New category</Button>} />
    <DataTable rows={data ?? []} keyField="id" columns={[{ key: "name", header: "Category", render: (c: any) => <span className={c.parentId ? "pl-6 text-ink/80" : "font-medium"}>{c.parentId ? "↳ " : ""}{c.name}</span> }, { key: "slug", header: "Slug", render: (c: any) => <span className="font-mono text-xs">/collections/{c.slug}</span> }, { key: "productCount", header: "Products" }, { key: "isActive", header: "Status", render: (c: any) => <StatusBadge status={c.isActive ? "ACTIVE" : "INACTIVE"} /> }, { key: "actions", header: "", render: (c: any) => can("PRODUCT_UPDATE") && <div className="flex justify-end gap-2"><Button size="sm" variant="ghost" onClick={() => setEdit({ ...c, parentId: c.parentId ?? "", description: c.description ?? "", imageUrl: c.imageUrl ?? "" })}>Edit</Button>{can("PRODUCT_DELETE") && <Button size="sm" variant="ghost" className="text-red-600" onClick={() => { if (confirm("Delete category?")) remove.mutate(c.id); }}>Delete</Button>}</div>, className: "text-right" }]} />
    <Dialog open={!!edit} onClose={() => setEdit(null)} title={edit?.id ? "Edit category" : "New category"}>{edit && <form className="space-y-3" onSubmit={(e) => { e.preventDefault(); save.mutate(edit); }}><Field label="Name"><Input required value={edit.name} onChange={(e) => setEdit({ ...edit, name: e.target.value })} /></Field><Field label="Slug"><Input value={edit.slug} onChange={(e) => setEdit({ ...edit, slug: e.target.value })} /></Field><Field label="Parent"><Select value={edit.parentId} onChange={(e) => setEdit({ ...edit, parentId: e.target.value })}><option value="">None (top level)</option>{parents.filter((p: any) => p.id !== edit.id).map((p: any) => <option key={p.id} value={p.id}>{p.name}</option>)}</Select></Field><Field label="Description"><Input value={edit.description} onChange={(e) => setEdit({ ...edit, description: e.target.value })} /></Field><Field label="Banner image URL"><Input value={edit.imageUrl} onChange={(e) => setEdit({ ...edit, imageUrl: e.target.value })} /></Field><div className="grid grid-cols-2 gap-3"><Field label="Sort order"><Input type="number" value={edit.sortOrder} onChange={(e) => setEdit({ ...edit, sortOrder: e.target.value })} /></Field><div className="pt-6"><Checkbox label="Active" checked={!!edit.isActive} onChange={(e) => setEdit({ ...edit, isActive: e.target.checked })} /></div></div><Button type="submit" className="w-full" loading={save.isPending}>Save</Button></form>}</Dialog></div>;
}
